[package]
name = "pspjs-runtime"
version = "0.1.0"
authors = ["Yifeng Wang <doodlewind@gmail.com>"]
edition = "2018"

[dependencies]
psp = { path = "../rust-psp/psp" }
libquickjs-sys = { path = "../quickjs-rs/libquickjs-sys" }

[build-dependencies]
cc = "1.0"
